export const FETCH_SERVICES_REQUEST = "FETCH_SERVICES_REQUEST";
export const FETCH_SERVICES_FAILURE = "FETCH_SERVICES_FAILURE";
export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const CHANGE_SERVICE_FIELD = "CHANGE_SERVICE_FIELD";
export const REMOVE_SERVICE = "REMOVE_SERVICE";
export const EDIT_SERVICE = "EDIT_SERVICE";
