export const FETCH_SERVICES_REQUEST = "FETCH_SERVICES_REQUEST";
export const FETCH_SERVICES_FAILURE = "FETCH_SERVICES_FAILURE";
export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const UPDATE_SERVICES = "UPDATE_SERVICES";

export const FETCH_SERVICE_REQUEST = "FETCH_SERVICE_REQUEST";
export const STOP_LOADING = "STOP_LOADING";

export const CHANGE_SERVICE_FIELD = "CHANGE_SERVICE_FIELD";
export const FETCH_CHANGE_SERVICE_REQUEST = "FETCH_CHANGE_SERVIC_REQUEST";
export const FETCH_CHANGE_SERVICES_SUCCESS = "FETCH_CHANGE_SERVICES_SUCCESS;";
