export const FETCH_SERVICES_REQUEST = "FETCH_SERVICES_REQUEST";
export const FETCH_SERVICES_FAILURE = "FETCH_SERVICES_FAILURE";
export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const FETCH_SERVICE_REQUEST = "FETCH_SERVICE_REQUEST";
export const REMOVE_SERVICE = "REMOVE_SERVICE";
export const UPDATE_SERVICES = "UPDATE_SERVICES";

export const CHANGE_SERVICE_FIELD = "CHANGE_SERVICE_FIELD";
